call compile preprocessFileLineNumbers "hc\HCsignals.sqf";
HCdo_spawnRCV = compile preprocessFileLineNumbers "hc\HCdo_spawnRCV.sqf";
call compile preprocessFileLineNumbers "hc\handle_HCdo_spawnRCV.sqf";
nearest_player = compile preprocessFileLineNumbers "hc\nearest_player.sqf";
zombie_loiterHC = compile preprocessFileLineNumbers "hc\zombie_loiterHC.sqf";
zombie_generateHC = compile preprocessFileLineNumbers "hc\zombie_generateHC.sqf";
building_spawnZombiesHC = compile preprocessFileLineNumbers "hc\building_spawnZombiesHC.sqf";
wild_spawnZombiesHC = compile preprocessFileLineNumbers "hc\wild_spawnZombiesHC.sqf";
player_spawnCheck = compile preprocessFileLineNumbers "hc\player_spawnCheck.sqf";
player_zombieAttack = compile preprocessFileLineNumbers "hc\player_zombieAttack.sqf";
